version: '2'
services: 
  ca-org1:
    image: hyperledger/fabric-ca:1.4.8
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org1.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-tls/tlsca.org1.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-tls/priv_sk
    ports: 
      - 7054:7054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'  
    volumes:
      - ./../../crypto-config/peerOrganizations/org1.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./../../crypto-config/peerOrganizations/org1.com/tlsca/:/etc/hyperledger/fabric-ca-server-tls
    container_name: ca.org1.com

  ca-org2:
    image: hyperledger/fabric-ca:1.4.8
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org2.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-tls/tlsca.org2.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-tls/priv_sk
    ports: 
      - 8054:7054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'  
    volumes:
      - ./../../crypto-config/peerOrganizations/org2.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./../../crypto-config/peerOrganizations/org2.com/tlsca/:/etc/hyperledger/fabric-ca-server-tls
    container_name: ca.org2.com
networks:
    default:
        external:
            name: fabric

